version: '2'
services:
  web:
    image: centos:nginx
    ports:
      - 8080:80
    volumes:
      - /srv/www:/srv/www
    links:
      - php

  php:
    image: centos:php
    volumes:
      - /srv/www:/srv/www
